Add missing dependency in Makefile
Otherwise building fails with:

pkg/bundled/inject.go:33:15: undefined: assets
pkg/bundled/inject.go:38:3: undefined: assets
pkg/bundled/inject.go:46:9: undefined: assets
pkg/bundled/inject.go:50:40: undefined: assets
pkg/bundled/inject.go:51:23: undefined: assets